// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWnU5o9KoM3vBLh9xSbMYfQfNJbQyvMk',
    appId: '1:104878832188:android:c7910df1ddbee9fa9be139',
    messagingSenderId: '104878832188',
    projectId: 'flatsync-1db9f',
    storageBucket: 'flatsync-1db9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4wX_Toma_qUXLeun-yYRAPBl4tjwDSjs',
    appId: '1:104878832188:ios:2d3a57f82d0b230d9be139',
    messagingSenderId: '104878832188',
    projectId: 'flatsync-1db9f',
    storageBucket: 'flatsync-1db9f.firebasestorage.app',
    iosBundleId: 'com.example.flatsyncApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDTX__8hblvS92AcVPIC5oVSa_RCc1WBXw",
    authDomain: "flatsync-1db9f.firebaseapp.com",
    projectId: "flatsync-1db9f",
    storageBucket: "flatsync-1db9f.firebasestorage.app",
    messagingSenderId: "104878832188",
    appId: "1:104878832188:web:4a18acbe5bec41ba9be139",
    measurementId: "G-877LDHMC1F"
    );

}